### PR TITLE
Greatly increased performance and robustness for big files

### PR DESCRIPTION
**Pull request by jonasViehweger**
Hi Ned,

I worked on your RF_Classification script with the main goal of adding multi-core processing. Along the way I also updated the base algorithm for randomly sampling the ground truth polygons and I completely rewrote how the random forest prediction is done.

These changes resulted in a much more robust algorithm for big raster and ground truth data with a greatly increased performance. Classifying the included sample data is more than twice as fast as the previous algorithm for single core processing, and up to 6 times faster using multi-core processing.

If you like you can review the changes and check for any bugs or mistakes. I would be happy if the changes could then be included in the main branch.

Any comments are greatly appreciated!

Thanks!

### CODE REVIEW

**Comment by nedhorning** [comment]
Hi Jonas,

I took a look at your changes and like what you did - thanks for taking the time to make these improvement. There are a few changes I was wondering if you would be willing to make. These are based on my preferences and if you don't think they're a good idea just let me know. If you think the changes make sense but don't want to add the changes I can try to do it.
--
In the variables section you note that the "The Classes are required to be sequential integers starting at 1". That doesn't seem to be the case so I'm not sure why that text was added. My preference is that users can use any class integers and that seems to be the way it is working.

In previous version I fixed the class and threshold images to be INT1U data type and the current version outputs floating point. Can you change it to INT1U or maybe INT2U?

The margin file is output as a GPKG file and I'm concerned that some users will not be familiar with that format. Would it be possible and sensible to use the same output format that users use for the input file with the training features? I can also just add a note about GPKG files in the script description if changing is too difficult.

The script throws an error if the output files exist. My preference is to overwrite files if they exist but perhaps it's best to add an option in the variables sections so users can choose if they want to overwrite or have an error.
--

Please let me know what you think.

All the best,

Ned

On 10/12/19 5:28 PM, jonasViehweger wrote:
EXTERNAL SENDER


Hi Ned,

I worked on your RF_Classification script with the main goal of adding multi-core processing. Along the way I also updated the base algorithm for randomly sampling the ground truth polygons and I completely rewrote how the random forest prediction is done.

These changes resulted in a much more robust algorithm for big raster and ground truth data with a greatly increased performance. Classifying the included sample data is more than twice as fast as the previous algorithm for single core processing, and up to 6 times faster using multi-core processing.

If you like you can review the changes and check for any bugs or mistakes. I would be happy if the changes could then be included in the main branch.

Any comments are greatly appreciated!

Thanks!

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/nedhorning/RandomForestForRemoteSensing/pull/1<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnedhorning%2FRandomForestForRemoteSensing%2Fpull%2F1&data=02%7C01%7Chorning%40amnh.org%7C5237903c69f14c7b337c08d74f5b2577%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637065125218000760&sdata=jXgCwClAXLhVpLJp9Z%2FsVjPtN7M05VPh6nBuncypbok%3D&reserved=0>

Commit Summary

  *   - Deleted old Version
  *   Added Sample Data
  *   Changed GT, added new RF Version
  *   Added function to create outpath
  *   Implemented input check and other small changes
  *   Cleaned up code and comments for pull request
  *   Renamed Version 3

File Changes

  *   D Downloads/randomForestClassification/.Rhistory<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnedhorning%2FRandomForestForRemoteSensing%2Fpull%2F1%2Ffiles%23diff-0&data=02%7C01%7Chorning%40amnh.org%7C5237903c69f14c7b337c08d74f5b2577%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637065125218010716&sdata=Ca%2F2tZzItNzIyK66A2Mx20s1aw7ZxNVFheRhHC0aDGs%3D&reserved=0> (198)
  *   A Downloads/randomForestClassification/Sample_Data/BALATON_FNF.gpkg<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnedhorning%2FRandomForestForRemoteSensing%2Fpull%2F1%2Ffiles%23diff-1&data=02%7C01%7Chorning%40amnh.org%7C5237903c69f14c7b337c08d74f5b2577%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637065125218010716&sdata=xDZWvhp3I03pMYdTdzMG2g5m9jG7Xh%2BOiC20HFDFJ0Y%3D&reserved=0> (0)
  *   A Downloads/randomForestClassification/Sample_Data/BALATON_FNF.tif<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnedhorning%2FRandomForestForRemoteSensing%2Fpull%2F1%2Ffiles%23diff-2&data=02%7C01%7Chorning%40amnh.org%7C5237903c69f14c7b337c08d74f5b2577%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637065125218010716&sdata=R0IKP9MYW5KjvEuUl5gH6rzvUEDn9MEuLAc9gHcLQ7Q%3D&reserved=0> (0)
  *   A Downloads/randomForestClassification/Sample_Data/BALATON_L8.tif<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnedhorning%2FRandomForestForRemoteSensing%2Fpull%2F1%2Ffiles%23diff-3&data=02%7C01%7Chorning%40amnh.org%7C5237903c69f14c7b337c08d74f5b2577%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637065125218020673&sdata=RAihTL74Dn%2Blypg%2BXVB0roHKmT%2FxScTmOSUABjsO4J8%3D&reserved=0> (0)
  *   M Downloads/randomForestClassification/rf_classification.R<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnedhorning%2FRandomForestForRemoteSensing%2Fpull%2F1%2Ffiles%23diff-4&data=02%7C01%7Chorning%40amnh.org%7C5237903c69f14c7b337c08d74f5b2577%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637065125218020673&sdata=VZN3iSgivEjRXKL3AAmcuiE9ZOLKUtxWFBez1Ah1yHs%3D&reserved=0> (464)
  *   D Downloads/randomForestClassification/rf_classification_v2.R<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnedhorning%2FRandomForestForRemoteSensing%2Fpull%2F1%2Ffiles%23diff-5&data=02%7C01%7Chorning%40amnh.org%7C5237903c69f14c7b337c08d74f5b2577%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637065125218030625&sdata=tKBfUlvOSjQ%2BS9dei37Ifj%2BM8AFlIqwG2J2wxvDOpqw%3D&reserved=0> (359)

Patch Links:

  *   https://github.com/nedhorning/RandomForestForRemoteSensing/pull/1.patch<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnedhorning%2FRandomForestForRemoteSensing%2Fpull%2F1.patch&data=02%7C01%7Chorning%40amnh.org%7C5237903c69f14c7b337c08d74f5b2577%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637065125218030625&sdata=ORSDc595AxitlaAXl9BsWQC%2BAvTTPjzrZFrEJ%2Big8qE%3D&reserved=0>
  *   https://github.com/nedhorning/RandomForestForRemoteSensing/pull/1.diff<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnedhorning%2FRandomForestForRemoteSensing%2Fpull%2F1.diff&data=02%7C01%7Chorning%40amnh.org%7C5237903c69f14c7b337c08d74f5b2577%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637065125218030625&sdata=fK%2F9YqAvU2WU%2FvLaurq2zHoj%2BKglKvf9CMM2%2F6yyJBU%3D&reserved=0>

**Comment by jonasViehweger** [comment]
Thanks for your response!

Concerning your suggestions: 

You're right that it isn't required anymore for the integers to be sequential starting at 1. It was true for an earlier version. I removed the comment from the section.

I also changed the default output data type for the rasters to INT2U.

My reasoning for changing the margin output from SHP to GPKG was due to (as far as I can tell) inherit limitations in the Shapefile format as well as the OGR conversion, which causes the "classNum" attribute to be saved as a real datatype instead of integer (So for example class 1 would be saved as an approximation of 1.000000 instead of 1). I do not know if this can be fixed for shapefiles using some creation options, but everything I've tried didn't deliver any promising results.
But I do like your suggestion of just outputting the same vector file format which was input so I changed the code accordingly (However the use of GPKG is strongly recommended ;) ).

Concerning the overwriting behaviour: There already exists a new boolean "overwrite" to choose your preferred behaviour. It is set to False by default.

Something that may still have to be done is updating the guide with the new information.

**Comment by nedhorning** [comment]
This all looks good. I did the merge so it should be all set.

I can't believe I didn't see the overwrite variable. Sorry about that.

I will work on updating the user guide and readme file and will send it to you before I load it to GitHub in case you have any comments. I'll make sure I add a section encouraging people to use GPKG files.

One question I have is with the sample data you uploaded. What is the purpose of the "BALATON_FNF.tif" file? It looks like it's a raster version of the GPKG file so I'm guessing it was used to create the GPKG polygons but wasn't sure why it is needed.

I'll also create an OldScript directory for the two previous scripts since I know some people still want to use the old scripts since they're used for training and instructors don't always want to change their guides.

Thanks again for your help. I'll try to get the document revisions done by the end of the week.

Ned

On 10/15/19 12:36 PM, jonasViehweger wrote:
EXTERNAL SENDER


Thanks for your response!

Concerning your suggestions:

You're right that it isn't required anymore for the integers to be sequential starting at 1. It was true for an earlier version. I removed the comment from the section.

I also changed the default output data type for the rasters to INT2U.

My reasoning for changing the margin output from SHP to GPKG was due to (as far as I can tell) inherit limitations in the Shapefile format as well as the OGR conversion, which causes the "classNum" attribute to be saved as a real datatype instead of integer (So for example class 1 would be saved as an approximation of 1.000000 instead of 1). I do not know if this can be fixed for shapefiles using some creation options, but everything I've tried didn't deliver any promising results.
But I do like your suggestion of just outputting the same vector file format which was input so I changed the code accordingly (However the use of GPKG is strongly recommended ;) ).

Concerning the overwriting behaviour: There already exists a new boolean "overwrite" to choose your preferred behaviour. It is set to False by default.

Something that may still have to be done is updating the guide with the new information.

**Comment by jonasViehweger** [comment]
Yeah it's true, the file "BALATON_FNF.tif" isn't really necessary, feel free to delete it. In my opinion it's also debateable if the sample data should be included in the github repository in the first place. But that's up to you to decide.

It was a lot of fun working on the script since this is the first time I really did something substantial in R, so it posed a good challenge to implement multiprocessing. Also thank you for all the input and corrections, they were really helpful.

**Comment by nedhorning** [comment]
Hi Jonas,

I updated the user guide and pushed it to the repo. If you have a chance to look at it please make comments/edits on the .odt file in the Guide folder. If you don't have time no worries.

All the best,

Ned

On 10/15/19 2:35 PM, jonasViehweger wrote:
EXTERNAL SENDER


Yeah it's true, the file "BALATON_FNF.tif" isn't really necessary, feel free to delete it. In my opinion it's also debateable if the sample data should be included in the github repository in the first place. But that's up to you to decide.

It was a lot of fun working on the script since this is the first time I really did something substantial in R, so it posed a good challenge to implement multiprocessing. Also thank you for all the input and corrections, they were really helpful.

**Pull request merged**
